name: Bounty
description: Bounty Hunter Needed
title: "Bounty Hunter Needed : [Enter Bounty Title here]"
labels: [bounty-hunter-needed]
assignees:
 Raised-By
body:
  - type: dropdown
    id: Bounty-Level
    attributes:
      label: Bounty-Level
      description: Bounty-Level
      options:
       - Urgent
       - Important
       - Useful
    validations:
      required: true
  - type: dropdown
    id: Complexity
    attributes:
      label: Complexity
      description: Complexity
      options:
       - High Complexity
       - Medium Complexity
       - Low Complexity
    validations:
      required: true
  - type: dropdown
    id: Bounty-Amount
    attributes:
      label: Bounty-Amount
      description: Bounty-Amount
      options:
       - 5 ADA
       - 10 ADA
       - 50 ADA
    validations:
      required: true
  - type: dropdown
    id: Bounty-Bonus
    attributes:
      label: Bounty Bonus
      description: Bounty Bonus
      options:
