name: Challenges
description: Challenges
title: "Challenges : [Enter here]"
labels: [Challenges]
assignees:
 Raised-By
body:
  - type: dropdown
    id: Challenges
    attributes:
      label: Challenges
      description: Challenges
      options:
       - Urgent
       - Important
       - Useful
    validations:
      required: true
  - type: dropdown
    id: Complexity
    attributes:
      label: Complexity
      description: Complexity
      options:
       - High Complexity
       - Medium Complexity
       - Low Complexity
    validations:
      required: true
  - type: dropdown
    id: Bounty-Amount
    attributes:
      label: Bounty-Amount
      description: Bounty-Amount
      options:
       - 5 ADA
       - 10 ADA
       - 50 ADA
    validations:
      required: true 
